using api_server.Controllers.Media.Dto;
using exs.Database.Commons.Interfaces;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using db_model.Media;

namespace api_server.Controllers.Media
{
	public interface IMediaInboundProcessor
	{
		/// <summary>
		/// Deletes the entries of dto.RemoveMediaIds that are also present in
		/// allowedRemoveIds (anything else in RemoveMediaIds is silently ignored — the
		/// caller decides what this request is entitled to remove, e.g. its own current
		/// AvatarImageId, not arbitrary ids a client could send) and creates a new
		/// UploadedMedia record for each entry in dto.InsertMedias, then persists both.
		/// Returns the newly created/loaded entities (with their DB-generated Id) so the
		/// caller can link them to whatever owns them.
		/// </summary>
		Task<List<UploadedMedia>> ProcessAsync(InboundMediaAttachableDto dto, IReadOnlyCollection<int> allowedRemoveIds, CancellationToken cancellationToken);
	}

	public sealed class MediaInboundProcessor : IMediaInboundProcessor
	{
		public MediaInboundProcessor(IRepository repository, IOptions<MediaSettings> settings, ILogger<MediaInboundProcessor> logger)
		{
			mRepository = repository;
			mSettings = settings.Value;
			mLogger = logger;
		}

		public async Task<List<UploadedMedia>> ProcessAsync(InboundMediaAttachableDto dto, IReadOnlyCollection<int> allowedRemoveIds, CancellationToken cancellationToken)
		{
			var context = mRepository.DbContext;
			var (result, removedFileNames) = await UploadedMediaTableLock.ExecuteAsync(context, async ct =>
			{
				// Filenames are captured before the delete so the physical files can be
				// removed once this is durably committed — deleting them inside the
				// transaction would leave orphaned-on-disk-but-gone-from-DB files (or
				// vice versa) if the execution strategy retries or the commit fails.
				var removedFileNames = new List<string>();
				if (dto.RemoveMediaIds is { Count: > 0 } removeIds)
				{
					var toRemove = removeIds.Where(allowedRemoveIds.Contains).ToList();
					if (toRemove.Count > 0)
					{
						var removedMedia = await mRepository.GetQueryable<UploadedMedia>(m => toRemove.Contains(m.Id))
							.ToListAsync(ct);
						removedFileNames.AddRange(removedMedia.Select(m => m.FileName));
						mRepository.DeleteAll(removedMedia);
					}
				}

				var result = new List<UploadedMedia>();
				if (dto.InsertMedias is { Count: > 0 } inserts)
				{
					var guids = inserts.Select(i => i.Guid).ToList();
					var existingByGuid = await mRepository.GetQueryable<UploadedMedia>(m => guids.Contains(m.Guid))
						.ToDictionaryAsync(m => m.Guid, ct);

					foreach (var insert in inserts)
					{
						if (existingByGuid.TryGetValue(insert.Guid, out var existing))
						{
							result.Add(existing);
							continue;
						}

						var media = new UploadedMedia
						{
							FileName = insert.Url,
							Guid = insert.Guid,
							MediaType = insert.MediaType,
							LatestUpdate = DateTime.UtcNow,
						};
						mRepository.Create(media);
						result.Add(media);
					}
				}

				await mRepository.SaveAsync(ct);
				return (result, removedFileNames);
			}, cancellationToken);

			foreach (var fileName in removedFileNames)
			{
				DeleteUploadedFile(fileName);
			}
			return result;
		}

		/// <summary>
		/// Best-effort: a file missing on disk (or never backed by one — InsertMedias
		/// can point at an external URL rather than an uploaded file) is not an error,
		/// and a failure here must not undo the already-committed DB delete.
		/// </summary>
		private void DeleteUploadedFile(string fileName)
		{
			if (string.IsNullOrEmpty(mSettings.UploadFolder) || fileName.Contains("://"))
			{
				return;
			}

			// FileName only ever holds a bare name generated by MediaStorageService, but
			// InsertMedias.Url is client-supplied — Path.GetFileName plus the post-combine
			// containment check below stop it from escaping UploadFolder via "..".
			var uploadFolder = Path.GetFullPath(mSettings.UploadFolder);
			var filePath = Path.GetFullPath(Path.Combine(uploadFolder, Path.GetFileName(fileName)));
			if (!filePath.StartsWith(uploadFolder, StringComparison.Ordinal))
			{
				return;
			}

			try
			{
				File.Delete(filePath);
			}
			catch (IOException ex)
			{
				mLogger.LogWarning(ex, "Failed to delete uploaded media file {FilePath}", filePath);
			}
			catch (UnauthorizedAccessException ex)
			{
				mLogger.LogWarning(ex, "Failed to delete uploaded media file {FilePath}", filePath);
			}
		}

		private readonly IRepository mRepository;
		private readonly MediaSettings mSettings;
		private readonly ILogger<MediaInboundProcessor> mLogger;
	}
}
